### PR TITLE
Fluent querying can lead to invalid entity graph if multiple children nodes of a same child node are queried #318

### LINKED ISSUE #318: Fluent querying can lead to invalid entity graph if multiple children nodes of a same child node are queried
### What steps will reproduce the problem ?
1. Build an entity graph with at least 2 children nodes from a same attribute.
2. Try calling a EntityGraphJpaSpecificationExecutor#findBy(Specification, EntityGraph, Function)
with it.

### What is the expected output ?
It should return the queried result.

### What happens instead ?
You end up with a org.springframework.data.core.PropertyReferenceException because it cannot find properties you asked for.

### Environment
 - Spring Data JPA version: 4.0.1
 - ORM version: Hibernate 7.3.1.Final
 - spring-data-jpa-entity-graph version: 4.0.3

### Additional context
Introduced by https://github.com/Cosium/spring-data-jpa-entity-graph/commit/4585c9778946fde8a8deeb9fa3365c6fca3c73b0

### PR DESCRIPTION
**Pull request by roman-garcia**
Fix #318

### CODE REVIEW

File: core/src/main/java/com/cosium/spring/data/jpa/entity/graph/domain2/EntityGraphQueryHint.java [hunk 1]
```diff
@@ -55,19 +57,27 @@ public final <T> SpecificationFluentQuery<T> applyTo(SpecificationFluentQuery<T>
...
-  private void addPath(AttributeNode<?> node, List<String> path) {
-    path.add(node.getAttributeName());
+  private void visitNode(
+      AttributeNode<?> node, @Nullable String parentPath, List<String> collectedPaths) {
+    String visitedPath =
+        Optional.ofNullable(parentPath)
+            .map(path -> path + "." + node.getAttributeName())
+            .orElseGet(node::getAttributeName);
+
+    if (node.getSubgraphs().isEmpty()) {
```
Comment (reda-alaoui) [inline core/src/main/java/com/cosium/spring/data/jpa/entity/graph/domain2/EntityGraphQueryHint.java]: Please factorize `node.getSubgraphs()`.

**Review by reda-alaoui — CHANGES_REQUESTED** [review]

**Review by reda-alaoui — APPROVED** [review]
